/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    TextAnalyzer: typeof import('./src/components/TextAnalyzer.vue')['default']
    WordCloudCanvas: typeof import('./src/components/WordCloudCanvas.vue')['default']
  }
}
