[package]
name = "wordcloud"
version = "0.2.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/GalAster/wordcloud-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
image = "0.23"
pix = "0.13"
rand = "0.7"

[dev-dependencies]

[features]
default = []
web = []
gpu = []