name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Instal LLVM
        run: choco install -y llvm
        if: runner.os == 'Windows'
      - name: Build
        run: cargo build --release
      - name: Tests
        run: cargo test --release